name: Continuous integration

on:
  - push
  - pull_request

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest

    outputs:
      changelog: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31.0.1

  build_project:
    name: Build project
    runs-on: ubuntu-latest

    needs: changelog
    if: |
      contains(needs.changelog.outputs.changelog, 'src') ||
      contains(needs.changelog.outputs.changelog, 'proto')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Generate protos
        run: make all

      - name: Build project
        run: |
          npm i
          npm run build

  release_version:
    name: Release version
    runs-on: ubuntu-latest
    
    needs: build_project
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        id: tagging
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagging.outputs.new_tag }}
          token: ${{ secrets.PAT }}